Fix/compatibility note
quarkiverse/quarkus-mockk pull request #118
Opened 2022-04-14 20:17 UTC by glefloch

2022-04-14 20:52 UTC, gsmet requested changes

2022-04-14 20:52 UTC, gsmet commented on README.md
> +## Compatibility with quarkus
```suggestion
## Compatibility with Quarkus
```

2022-04-14 20:52 UTC, gsmet commented on README.md
> +Starting from quarkus `2.8` and above, version `1.1.0` of `quarkus-junit5-mockk` should be use.
```suggestion
Starting with Quarkus `2.8` and above, version `1.1.0` of `quarkus-junit5-mockk` should be used. 
```

2022-04-14 20:52 UTC, gsmet commented on README.md
> +If you use a version before `2.7`, version `1.0.1` of `quarkus-junit5-mockk` should be use.
```suggestion
If you use a version before `2.7`, version `1.0.1` of `quarkus-junit5-mockk` should be used.
```

2022-04-14 20:52 UTC, gsmet commented on docs/modules/ROOT/pages/index.adoc
> +If you use a version before `2.7`, version `1.0.1` of `quarkus-junit5-mockk` should be use.
```suggestion
== Compatibility with Quarkus

Starting with Quarkus `2.8` and above, version `1.1.0` of `quarkus-junit5-mockk` should be used.
If you use a version before `2.7`, version `1.0.1` of `quarkus-junit5-mockk` should be used.
```

2022-04-15 12:46 UTC, glefloch commented
Thanks for the review @gsmet I pushed fixes

2022-04-15 13:05 UTC, gsmet approved these changes

2022-04-15 13:05 UTC, merged